version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: character_db
    ports:
      - "5432:5432"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d character_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build: ./character-creator/backend
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - my-network
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: character_db
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3000

  frontend:
    build: ./character-creator/frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:

