version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: character_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./character-creator/backend
    container_name: backend_service
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./character-creator/frontend
    container_name: frontend_service
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:

